// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TreeListBoxTests.cs" company="PropertyTools">
//   Copyright (c) 2014 PropertyTools contributors
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace PropertyTools.Wpf.Tests
{
    using System.Collections.ObjectModel;

    using NUnit.Framework;

    using PropertyTools.Wpf;

    /// <summary>
    /// Headless component tests for <see cref="TreeListBox" />.
    /// </summary>
    public class TreeListBoxTests : WpfTestBase
    {
        [Test]
        public void HierarchySource_TwoRootItems_PopulatesRootItemsOnly()
        {
            // Arrange
            var treeListBox = new TreeListBox { ChildrenPath = nameof(Node.Children) };
            var source = new ObservableCollection<Node>
            {
                new Node("Root1") { Children = { new Node("Child1"), new Node("Child2") } },
                new Node("Root2")
            };

            // Act
            treeListBox.HierarchySource = source;

            // Assert
            Assert.That(treeListBox.Items.Count, Is.EqualTo(2), "Only the (collapsed) root items should be in the flat list");
        }

        [Test]
        public void HierarchySource_SetToNull_ClearsItems()
        {
            // Arrange
            var treeListBox = new TreeListBox { ChildrenPath = nameof(Node.Children) };
            treeListBox.HierarchySource = new ObservableCollection<Node> { new Node("Root1") };

            // Act
            treeListBox.HierarchySource = null;

            // Assert
            Assert.That(treeListBox.Items.Count, Is.EqualTo(0));
        }

        [Test]
        public void HierarchySource_AddRootItem_ItemsAreUpdated()
        {
            // Arrange
            var source = new ObservableCollection<Node> { new Node("Root1") };
            var treeListBox = new TreeListBox { ChildrenPath = nameof(Node.Children), HierarchySource = source };

            // Act
            source.Add(new Node("Root2"));

            // Assert
            Assert.That(treeListBox.Items.Count, Is.EqualTo(2));
        }

        [Test]
        public void IsExpanded_SetOnRootContainer_AddsChildrenToItems()
        {
            // Arrange
            var treeListBox = new TreeListBox { ChildrenPath = nameof(Node.Children) };
            var root = new Node("Root1") { Children = { new Node("Child1"), new Node("Child2") } };
            treeListBox.HierarchySource = new ObservableCollection<Node> { root };
            PrepareForLayout(treeListBox);
            DoEvents();

            var container = treeListBox.ItemContainerGenerator.ContainerFromIndex(0) as TreeListBoxItem;
            Assert.That(container, Is.Not.Null, "The root item container should be generated by the layout pass");

            // Act
            container.IsExpanded = true;

            // Assert
            Assert.That(treeListBox.Items.Count, Is.EqualTo(3), "Expanding the root should add its children to the flat list");
        }

        [Test]
        public void IsExpanded_ClearedOnRootContainer_RemovesChildrenFromItems()
        {
            // Arrange
            var treeListBox = new TreeListBox { ChildrenPath = nameof(Node.Children) };
            var root = new Node("Root1") { Children = { new Node("Child1") } };
            treeListBox.HierarchySource = new ObservableCollection<Node> { root };
            PrepareForLayout(treeListBox);
            DoEvents();

            var container = treeListBox.ItemContainerGenerator.ContainerFromIndex(0) as TreeListBoxItem;
            Assert.That(container, Is.Not.Null);
            container.IsExpanded = true;
            Assert.That(treeListBox.Items.Count, Is.EqualTo(2));

            // Act
            container.IsExpanded = false;

            // Assert
            Assert.That(treeListBox.Items.Count, Is.EqualTo(1), "Collapsing the root should remove its children from the flat list");
        }

        /// <summary>
        /// A simple hierarchical model used by the tests.
        /// </summary>
        private class Node
        {
            public Node(string name)
            {
                this.Name = name;
            }

            public string Name { get; }

            public ObservableCollection<Node> Children { get; } = new ObservableCollection<Node>();

            public override string ToString() => this.Name;
        }
    }
}
