//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataGridDemo.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Boolean {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Color {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_DateTime {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Fruit {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruits*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Fruits {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Integer {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Items {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Mass {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Number {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlyBoolean*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_ReadOnlyBoolean {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.ReadOnlyBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlyInteger*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_ReadOnlyInteger {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.ReadOnlyInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnlyString*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_ReadOnlyString {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.ReadOnlyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_Selector {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String*.
        /// </summary>
        internal static string DataGridDemo_ExampleObject_String {
            get {
                return ResourceManager.GetString("DataGridDemo.ExampleObject.String", resourceCulture);
            }
        }
    }
}
