<Project>
  <PropertyGroup>
    <AssemblyName>PropertyTools.Wpf</AssemblyName>
    <IntermediateOutputPath>obj/Debug/net9.0-windows/</IntermediateOutputPath>
    <BaseIntermediateOutputPath>obj/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>/home/runner/work/PropertyTools/PropertyTools/Source/PropertyTools.Wpf/obj/</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>PropertyTools.Wpf</_TargetAssemblyProjectName>
    <RootNamespace>PropertyTools.Wpf</RootNamespace>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
    <TargetFrameworks>net462;net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>PropertyTools.snk</AssemblyOriginatorKeyFile>
    <Description>Custom controls for WPF: PropertyGrid, DataGrid, multi-select TreeView, ColorPicker and more</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/PropertyTools/PropertyTools/</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>wpf controls propertygrid dataform datagrid treeview colorpicker</PackageTags>
    <Version>0.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\Images\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PropertyTools\PropertyTools.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="PropertyTools.snk" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/Accessibility.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/Microsoft.CSharp.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/Microsoft.VisualBasic.Core.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/Microsoft.VisualBasic.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/Microsoft.Win32.Primitives.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/Microsoft.Win32.Registry.AccessControl.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/Microsoft.Win32.Registry.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/Microsoft.Win32.SystemEvents.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/mscorlib.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/netstandard.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationCore.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.Aero.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.Aero2.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.AeroLite.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.Classic.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.Luna.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationFramework.Royale.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/PresentationUI.dll" />
    <ReferencePath Include="/home/runner/work/PropertyTools/PropertyTools/Source/PropertyTools/bin/Debug/netstandard2.0/PropertyTools.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/ReachFramework.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.AppContext.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Buffers.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.CodeDom.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Collections.Concurrent.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Collections.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Collections.Immutable.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Collections.NonGeneric.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Collections.Specialized.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ComponentModel.Annotations.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ComponentModel.DataAnnotations.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ComponentModel.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ComponentModel.EventBasedAsync.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ComponentModel.Primitives.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ComponentModel.TypeConverter.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Configuration.ConfigurationManager.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Configuration.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Console.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Core.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Data.Common.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Data.DataSetExtensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Data.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.Contracts.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.Debug.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.DiagnosticSource.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Diagnostics.EventLog.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.FileVersionInfo.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Diagnostics.PerformanceCounter.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.Process.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.StackTrace.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.TextWriterTraceListener.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.Tools.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.TraceSource.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Diagnostics.Tracing.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.DirectoryServices.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Drawing.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Drawing.Primitives.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Dynamic.Runtime.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Formats.Asn1.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Formats.Nrbf.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Formats.Tar.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Globalization.Calendars.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Globalization.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Globalization.Extensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Compression.Brotli.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Compression.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Compression.ZipFile.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.FileSystem.AccessControl.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.FileSystem.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.FileSystem.DriveInfo.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.FileSystem.Primitives.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.FileSystem.Watcher.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.IsolatedStorage.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.MemoryMappedFiles.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.IO.Packaging.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Pipelines.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Pipes.AccessControl.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.Pipes.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.IO.UnmanagedMemoryStream.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Linq.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Linq.Expressions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Linq.Parallel.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Linq.Queryable.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Memory.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Http.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Http.Json.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.HttpListener.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Mail.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.NameResolution.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.NetworkInformation.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Ping.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Primitives.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Quic.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Requests.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Security.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.ServicePoint.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.Sockets.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.WebClient.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.WebHeaderCollection.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.WebProxy.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.WebSockets.Client.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Net.WebSockets.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Numerics.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Numerics.Vectors.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ObjectModel.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Printing.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.DispatchProxy.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.Emit.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.Emit.ILGeneration.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.Emit.Lightweight.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.Extensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.Metadata.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.Primitives.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Reflection.TypeExtensions.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Resources.Extensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Resources.Reader.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Resources.ResourceManager.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Resources.Writer.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.CompilerServices.Unsafe.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.CompilerServices.VisualC.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Extensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Handles.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.InteropServices.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.InteropServices.JavaScript.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.InteropServices.RuntimeInformation.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Intrinsics.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Loader.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Numerics.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Serialization.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Serialization.Formatters.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Serialization.Json.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Serialization.Primitives.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Runtime.Serialization.Xml.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.AccessControl.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Claims.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.Algorithms.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.Cng.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.Csp.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.Encoding.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.OpenSsl.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Security.Cryptography.Pkcs.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.Primitives.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Security.Cryptography.ProtectedData.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Cryptography.X509Certificates.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Security.Cryptography.Xml.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Security.Permissions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Principal.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.Principal.Windows.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Security.SecureString.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ServiceModel.Web.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ServiceProcess.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Text.Encoding.CodePages.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Text.Encoding.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Text.Encoding.Extensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Text.Encodings.Web.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Text.Json.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Text.RegularExpressions.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Threading.AccessControl.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Channels.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Overlapped.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Tasks.Dataflow.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Tasks.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Tasks.Extensions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Tasks.Parallel.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Thread.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.ThreadPool.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Threading.Timer.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Transactions.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Transactions.Local.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.ValueTuple.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Web.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Web.HttpUtility.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Windows.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Windows.Extensions.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Windows.Input.Manipulations.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Windows.Presentation.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/System.Xaml.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.Linq.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.ReaderWriter.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.Serialization.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.XDocument.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.XmlDocument.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.XmlSerializer.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.XPath.dll" />
    <ReferencePath Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/ref/net9.0/System.Xml.XPath.XDocument.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/UIAutomationClient.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/UIAutomationClientSideProviders.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/UIAutomationProvider.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/UIAutomationTypes.dll" />
    <ReferencePath Include="/home/runner/.nuget/packages/microsoft.windowsdesktop.app.ref/9.0.18/ref/net9.0/WindowsBase.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="/home/runner/work/PropertyTools/PropertyTools/Source/PropertyTools.Wpf/obj/Debug/net9.0-windows/Dialogs/PropertyDialog.g.cs" />
    <Compile Include="/home/runner/work/PropertyTools/PropertyTools/Source/PropertyTools.Wpf/obj/Debug/net9.0-windows/Dialogs/WizardDialog.g.cs" />
    <Compile Include="/home/runner/work/PropertyTools/PropertyTools/Source/PropertyTools.Wpf/obj/Debug/net9.0-windows/GeneratedInternalTypeHelper.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="/usr/share/dotnet/sdk/10.0.302/Sdks/Microsoft.NET.Sdk/targets/../analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll" />
    <Analyzer Include="/usr/share/dotnet/sdk/10.0.302/Sdks/Microsoft.NET.Sdk/targets/../analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll" />
    <Analyzer Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/analyzers/dotnet/cs/Microsoft.Interop.ComInterfaceGenerator.dll" />
    <Analyzer Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/analyzers/dotnet/cs/Microsoft.Interop.JavaScript.JSImportGenerator.dll" />
    <Analyzer Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/analyzers/dotnet/cs/Microsoft.Interop.LibraryImportGenerator.dll" />
    <Analyzer Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/analyzers/dotnet/cs/Microsoft.Interop.SourceGeneration.dll" />
    <Analyzer Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll" />
    <Analyzer Include="/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/9.0.18/analyzers/dotnet/cs/System.Text.RegularExpressions.Generator.dll" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>