<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputType>WinExe</OutputType>
    <Description>PropertyGrid undo/redo demo</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\PropertyTools.Wpf\PropertyTools.Wpf.csproj" />
    <ProjectReference Include="..\..\..\PropertyTools\PropertyTools.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Caliburn.Micro" Version="4.0.212" />
    <PackageReference Include="DotNetProjects.Extended.Wpf.Toolkit" Version="5.0.129" />
  </ItemGroup>
</Project>